debug: false
server:
  port: 8001
  
# mybatis 映射文件配置
mybatis:
  config-location: classpath:mybatis/mybatisConfig.xml
  type-aliases-package: com.xywei.domain #mybatis扫描该包下所有实体类
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
# 数据源配置 
spring:
  application:
    name: imicroservice-person
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源类型
    driver-class-name: org.gjt.mm.mysql.Driver #mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/clouddb01
    username: root
    password: xieSHI2019
#连接池设置
    dbcp2:
      min-idle: 5 #连接池内保持的最小连接数
      initial-size: 5 #初始化连接数
      max-idle: 5 # 最大连接数
      max-wait-millis: 500 #等待获取连接的最长时间